package magazyn.lab2;

public class Item implements Comparable<Item> {
    private String name;
    private ItemCondition condition;
    private double weight;
    private int count;

    public Item(String nazwa, ItemCondition stan, double masa, int ilosc) {
        this.name = nazwa;
        this.condition = stan;
        this.weight = masa;
        this.count = ilosc;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ItemCondition getCondition() {
        return condition;
    }

    public void setCondition(ItemCondition condition) {
        this.condition = condition;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    @Override
    public String toString() {
        //Autogenerated
        return "Item{" +
                "nazwa='" + name + '\'' +
                ", stan=" + condition +
                ", masa=" + weight +
                ", ilosc=" + count +
                '}';
    }

    @Override
    public int compareTo(Item o) {
        return this.getName().compareTo(o.getName());
    }
}
